#!/usr/bin/env bash
# This Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
#


echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

echo -e "\nSetting up some stuff here and there.\n"

# This is starting nginx service
sudo service nginx start

# This is allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# this gives the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# This backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# This is creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# This is setting up /redirect_me to a youtube video
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# This is Restarting nginx
sudo service nginx restart

echo -e "\nCompleted.\n"