#!/usr/bin/env bash
# A bash script that configures an ubuntu server

grep -v "localhost" /etc/hosts > hosts
echo -e "127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com" > /etc/hosts
cat hosts >> /etc/hosts
rm -rf hosts
