#!/usr/bin/env bash
# Script that lets nginx to run as nginx user and not root
pkill apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx nginx